"""empty message

Revision ID: 427187a8ae45
Revises: 4c400704d2ef
Create Date: 2022-08-17 18:31:41.760191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427187a8ae45'
down_revision = '4c400704d2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('experience', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'experience')
    # ### end Alembic commands ###
