"""empty message

Revision ID: 67319b88660d
Revises: 74101aa9299b
Create Date: 2022-08-17 18:29:26.367235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67319b88660d'
down_revision = '74101aa9299b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trustScore', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trustScore')
    # ### end Alembic commands ###
