"""empty message

Revision ID: 74101aa9299b
Revises: f576022e0981
Create Date: 2022-08-17 18:29:05.004278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74101aa9299b'
down_revision = 'f576022e0981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trustScore', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trustScore')
    # ### end Alembic commands ###
