"""empty message

Revision ID: b80d324f4741
Revises: 5cdee82a10e5
Create Date: 2022-08-17 00:20:23.516810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80d324f4741'
down_revision = '5cdee82a10e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('listedAt', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'listedAt')
    # ### end Alembic commands ###
