"""empty message

Revision ID: f576022e0981
Revises: 76487fd6a436
Create Date: 2022-08-17 00:25:09.826775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f576022e0981'
down_revision = '76487fd6a436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
